[project]
name = "pydantic-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jay" }
]
requires-python = ">=3.14"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.141.1",
    "pydantic>=2.13.5",
]

[project.scripts]
pydantic-basics = "pydantic_basics:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
